# fly.toml app configuration file generated for aurora-server-spring-hill-5575 on 2024-02-16T02:15:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aurora-server-spring-hill-5575'
primary_region = 'ewr'
kill_signal = 'SIGINT'
kill_timeout = '30s'

[build]

[env]
  PORT = '3000'
  SNAPSHOT = '2024-02-09'

[http_service]
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
